{% set name = "bumps" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27c35e57d142502e5d2e4a2c07356ba2fc622496deba3f17739d0d18423d066b
  patches:
    - scripts.patch # use entry points instead of installing scripts

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - bumps = bumps.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - six
  run:
    - python >=3.6
    - six
    - numpy
    - scipy

test:
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer

about:
  home: http://www.reflectometry.org/danse/software.html
  license: CC-PDDC
  summary: Data fitting with bayesian uncertainty analysis
  doc_url: https://bumps.readthedocs.io/en/latest/
  dev_url: https://github.com/bumps/bumps

extra:
  recipe-maintainers:
    - tschoonj
    - bmaranville
    - mrakitin
