travis:
  secure:
    BINSTAR_TOKEN: V0xf3lZp0yB44ml2Ce7PDlkicq/ThDt4EpbtqG1HjjXBJR6yGgY7lziX0mRrxw0Vcv12+eNBHrvMvH8qVsTEwrR2FFIbn7ZVLxqXoaGBA8FzQK4JMFitFQtRSLUzA4PxJNGByIPCW/IPmBVoo8v0pRNEpqkL9TKfE8/trN8OWzOXc+XRPLt3+Zw4crweJNN0qi8fqDUeLypjqkOaX5C1Fg4TEBb9Ss4OnGGMvQ3s4jn1m7irXtlaCFJYs5Dri7NNOu/yHMoPMFawWrR0aOHU2MpCdev2MZ7uSpsQoJ9ICCcMhQskCFWs9LVGSwF6kKsuu5GzyHZQaX8XOJR8LOuDTJqc0D5G9z3EaaNd9IXx8+HqsO5At/MjNji77drhXjwRxHdK8ipk/F86goSEvfUnyuk/EJ4jBgX8EVH2E+JCWJh0s1tojRlGSqx+CZAOXtCK9AaI//CG1Tdi7ecB9hmRRcfhdVa1MpP1QDJR9vJfgZbw0meMzOFfWvy5ZkhWX8SgiOGptZ8Bu64j5IFZiIWU+aGbn0HYeL6MsjtykgPuA1UvXrTRvkWO+8iIdBnNPyRKOva4wPM8Aoc52oQj2EyZ9ztKRwQ6A42OSfziuDLVJaxq/6Cl+hyMCL9QWJ9pzPfQR4L3jz+wSNjgruE3OL93Pj89EMTu9zkqL3YKQxmSeks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
